-- Supabase Schema for DChan's Safespace

-- 1. Users table (Simple PIN-based access for now)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY DEFAULT auth.uid(),
  user_name TEXT DEFAULT 'Hadassah',
  passcode TEXT DEFAULT '1122',
  email TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Journal Entries
CREATE TABLE IF NOT EXISTS public.journal_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  date TIMESTAMPTZ DEFAULT now(),
  mood_id TEXT NOT NULL,
  struggle TEXT,
  affirmation JSONB,
  thoughts TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Ebenezer Stones
CREATE TABLE IF NOT EXISTS public.ebenezer_stones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  date TIMESTAMPTZ DEFAULT now(),
  note TEXT,
  intensity FLOAT DEFAULT 0.5,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Gratitude Grains
CREATE TABLE IF NOT EXISTS public.gratitude_grains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  date TIMESTAMPTZ DEFAULT now(),
  text TEXT,
  type TEXT DEFAULT 'gratitude', -- 'gratitude' or 'word'
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Spanish Words
CREATE TABLE IF NOT EXISTS public.spanish_words (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  phrase TEXT NOT NULL,
  translation TEXT,
  context TEXT,
  type TEXT DEFAULT 'Spanish', -- 'Spanish' or 'English'
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Game Progress
CREATE TABLE IF NOT EXISTS public.game_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  game_type TEXT NOT NULL,
  item_id TEXT NOT NULL,
  completed_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Settings
CREATE TABLE IF NOT EXISTS public.user_settings (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE DEFAULT auth.uid(),
  bible_version TEXT DEFAULT 'ESV',
  voice_rate FLOAT DEFAULT 0.9,
  voice_pitch FLOAT DEFAULT 1.1,
  preferred_bike TEXT DEFAULT 'adventure',
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ebenezer_stones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gratitude_grains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.spanish_words ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;

-- Create basic RLS policies (Owner can see/edit their own data)
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can view own entries" ON public.journal_entries FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own entries" ON public.journal_entries FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own entries" ON public.journal_entries FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own entries" ON public.journal_entries FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own stones" ON public.ebenezer_stones FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own stones" ON public.ebenezer_stones FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own stones" ON public.ebenezer_stones FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own grains" ON public.gratitude_grains FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own grains" ON public.gratitude_grains FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own grains" ON public.gratitude_grains FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own words" ON public.spanish_words FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own words" ON public.spanish_words FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete own words" ON public.spanish_words FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can view own progress" ON public.game_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own progress" ON public.game_progress FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own settings" ON public.user_settings FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own settings" ON public.user_settings FOR ALL USING (auth.uid() = id);
